challenger.home:
  path:     /
  defaults:
    _controller: 'Metamoris\Controllers\ChallengerController::homeAction'

challenger.tabs.createaccount:
  path:     /createaccount
  defaults:
    _controller: 'Metamoris\Controllers\ChallengerController::tabFormsAction'
    activeTab: 'register'

challenger.tabs.login:
  path:     /login
  defaults:
    _controller: 'Metamoris\Controllers\ChallengerController::tabFormsAction'
    activeTab: 'login'

challenger.tabs.reset:
  path:     /reset
  defaults:
    _controller: 'Metamoris\Controllers\ChallengerController::tabFormsAction'
    activeTab: 'reset'

challenger.tabs.reset-password:
  path:     /reset-password/{token}
  defaults:
    _controller: 'Metamoris\Controllers\ChallengerController::resetPasswordAction'
    activeTab: 'reenter'
    token: ''

challenger.check-email:
  path:     /check-email
  defaults:
    _controller: 'Metamoris\Controllers\ChallengerController::checkEmailAction'

challenger.registration:
  path:     /registration
  defaults:
    _controller: 'Metamoris\Controllers\ChallengerController::registrationAction'

challenger.registration.payment:
  path:     /registration/payment
  defaults:
    _controller: 'Metamoris\Controllers\ChallengerController::paymentAction'

challenger.registration.confirmation:
  path:     /registration/confirmation
  defaults:
    _controller: 'Metamoris\Controllers\ChallengerController::confirmationAction'


challenger.registration.weight_classes:
  path:     /registration/fetch-weight-classes
  defaults:
    _controller: 'Metamoris\Controllers\ChallengerController::fetchWeightClassesAction'
